#!/usr/bin/env sh

source "./private/rotate_access_key"

function rotate() {
  set_preferences "$@"

  print "Running in verbose mode"

  print "Fetching existing access tokens..."
  local keys=$(run_iam_command list-access-keys | jq '.AccessKeyMetadata' -r)
  print "Found keys $keys"
  local key_length=$(echo $keys | jq '. | length')

  case $key_length in
    0) create_and_run_callback;;
    1) rotate_single_key $(echo "$keys" | jq '. | first | .AccessKeyId' -r);;
    2) remove_key_and_rotate "$keys";;
    *)
      echoerr "Unexpected amount of existing tokens: $key_length. exiting..."
      echoerr "Keys found: $keys"
      exit 0
      ;;
  esac
  print "Access key successfully rotated"
}
